
name: test

on: [ push, pull_request ]

jobs:

  test:

    if: " ! (contains(github.event.head_commit.message, 'skip ci') || contains(github.event.head_commit.message, 'ci skip'))"

    name: ${{matrix.ruby}} on ${{matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ '2.2.6', '2.3', '2.7', '3.0', '3.1', '3.2', 'jruby-9.2', 'jruby-9.4', 'truffleruby-22.3' ]
        experimental: [ false ]
      fail-fast: false
    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.experimental}}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: bundle exec rspec --force-color --format documentation

